### ISSUE TITLE
Grandchild routes lose their notifications from the dispatcher.

### ISSUE THREAD

**Issue by acidbluebriggs** [tfrydrychewicz/aurelia-flux#8]
I have an example of an application which has a grandchild route. This route only receives one event from the dispatcher. Attempting to navigate to another grandchild will result in no messages received from the dispatcher.

https://rawgit.com/acidbluebriggs/aurelia-flux-example/dist/
(code can be retrieved at: https://github.com/acidbluebriggs/aurelia-flux-example/tree/dist)

To reproduce:

Click on the Child link ( a child view will display, in an ugly manner).
Click on on of its descendants in the bulleted list.

The outcome is that a descendant receives the event from the dispatcher that an item has been selected.

Attempting to select another grandchild (same level as the previous selection) will result in no messages from the store to the child though the store has requested the dispatcher dispatch the event.

**Comment by victorarbuesmallada** [comment]
Getting a similar issue.
I got some router modules that get data on the activate method.

Basically the activate dispatch an event that ends up setting up an object on that module.
You can find the code for this here:
http://stackoverflow.com/questions/32994849/aurelia-flux-dispatch-only-call-once-on-activate-method

I'm assuming that maybe the activate method has something to do with it as I'm not getting that error if I move the dispatch to a different method.
Can anyone shed some light over this?

**Comment by victorarbuesmallada** [comment]
I managed to figure it out.

It seems that the module with the handler gets deactivated at some point and by doing that you miss the handler when an event is dispatched. In my case is when I move from one route item to another.

That handler module being also the one with the router might provoke this, since it's deactivated after a while.

**Comment by victorarbuesmallada** [comment]
If someone else encounters this issue, my solution was moving handling methods from a routing module.
Navigation provokes deactivation which provokes aurelia-flux to remove any handlers that get deactivated.
